"""Add PickAssignment table

Revision ID: 83fabbe397a1
Revises: 2b3fda096311
Create Date: 2026-02-10 16:51:41.601317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fabbe397a1'
down_revision = '2b3fda096311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_number', sa.String(length=50), nullable=False),
    sa.Column('handling_code', sa.String(length=50), nullable=True),
    sa.Column('picker_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['picker_id'], ['pickster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick_assignments')
    # ### end Alembic commands ###
