"""Add user_type to Pickster

Revision ID: 2b3fda096311
Revises: 3e6c5d3f8ce5
Create Date: 2026-02-10 11:09:51.433041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3fda096311'
down_revision = '3e6c5d3f8ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickster', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
