"""Initial migration

Revision ID: 3e6c5d3f8ce5
Revises: 
Create Date: 2026-02-10 11:00:11.977498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6c5d3f8ce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PickTypes',
    sa.Column('pick_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('pick_type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('pickster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.Column('barcode_number', sa.String(length=120), nullable=False),
    sa.Column('picker_id', sa.Integer(), nullable=False),
    sa.Column('pick_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pick_type_id'], ['PickTypes.pick_type_id'], ),
    sa.ForeignKeyConstraint(['picker_id'], ['pickster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pick_completed_time'), ['completed_time'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_number', sa.String(length=128), nullable=False),
    sa.Column('work_order_number', sa.String(length=128), nullable=False),
    sa.Column('item_number', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['pickster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_orders')
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pick_completed_time'))

    op.drop_table('pick')
    op.drop_table('pickster')
    op.drop_table('PickTypes')
    # ### end Alembic commands ###
